spring:
  cloud:
    gateway:
      routes:
        - id: cookie_route
          uri: https://example.org
          predicates:
            - Cookie=mycookie, mycookievalue
#            - name: Cookie
#              args:
#                name: mycookie
#                regexp: mycookievalue