spring:
  cloud:
    gateway:
      routes:
        - id: add_request_header_route
          uri: http://localhost:8081
          predicates:
            - Path=/hello/addHeader
          filters:
            - AddRequestHeader=X-Request-Acme, ValueB