# tomcat config
server:
  port: 8080
# spring config
spring:
  application:
    name: api-show-case
  profiles:
    active: dev
### sss logstash config
sss:
  logstash:
    enabled: true
    host: 127.0.0.1
    port: 8888
    queueSize: 512
    network-interface: eth0
