server:
  port: 8080
spring:
  profiles:
    active: dev
--- #spring datasource config ---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.100:3306/study?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    jpa:
      show-sql: true
--- #liquibase configuration ---
spring:
  liquibase:
    contexts: dev,test
    enabled: true
--- # logging configuration ---
logging:
  level:
    root: info
    liquibase: WARN
    org.hibernate.SQL: trace
---  # spring data jpa configuration ---
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
