server:
  port: 8080
spring:
  profiles:
    active: dev
--- #spring datasource config ---
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/study?useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: root
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        connection-test-query: SELECT 1 FROM DUAL
        minimum-idle: 1
        maximum-pool-size: 50
        idleTimeout: 120000
        connectionTimeout: 300000
        leakDetectionThreshold: 300000
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
--- #liquibase configuration ---
spring:
  liquibase:
    contexts: dev,test
    enabled: false
--- # logging configuration ---
logging:
  level:
    root: info
    liquibase: WARN
    org.hibernate.SQL: trace
---  # spring data jpa configuration ---
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
