### 获取授权码 （使用浏览器访问）
GET http://127.0.0.1:9090/oauth2/authorize?client_id=oidc-client&response_type=code&scope=user.info+openid&redirect_uri=http://127.0.0.1:8080/login/oauth2/code/oidc-client

### 获取token （Postman 调用）
POST http://127.0.0.1:9090/oauth2/token
Authorization: Basic b2lkYy1jbGllbnQ6MTIzNDU2
Content-Type: application/x-www-form-urlencoded
Accept: */*

grant_type=authorization_code
    &redirect_uri=http%3A%2F%2F127.0.0.1%3A8080%2Flogin%2Foauth2%2Fcode%2Foidc-client
    &code=8rIq44rqc0yxiYY7ZwSyaKhylwJwqbImt1yLdJkWNZxWhi9QSdrSS0x6L0ompXhGapI-Kf-DtJpcmapenRucoU7OyvuYc_LX8zMufDlTyTqXTozNQOylaykSHq-puw9j