### 获取token （默认不支持）
POST http://127.0.0.1:9090/oauth2/token
Authorization: Basic b2lkYy1jbGllbnQ6MTIzNDU2
Content-Type: application/x-www-form-urlencoded
Accept: */*

grant_type=password&username=admin&password=123456&scope=all&client_id=oidc-client